### ISSUE TITLE
Getting PHP error on newer Redcap version

### ISSUE THREAD

**Issue by marcuslehr** [dr01d3r/redcap-em-orca-call-list#8]
Hi, I was hoping to test this module but upon enabling I'm getting a PHP error. I tried making a new project from the classic template with no other EMs enabled. Our server info is REDCap 14.9.1 · PHP 8.0.30 (Linux/Unix OS) · MariaDB 10.5.22.

![image](https://github.com/user-attachments/assets/8e54e68c-ec30-4ea4-a5b7-9bfa90b0c7ee)

**Comment by marcuslehr** [comment]
Nevermind, I got it working by creating the fields described in the readme (call_date/contact_result). Would be nice if the module created those automatically when enabling or if that requirement was described on the config page or something.

**Comment by dr01d3r** [comment]
Apologies for the delay here @marcuslehr but glad you were able to resolve the issue.  We will look into making the requirements a bit more front & center, or allow the module to fail a bit more gracefully while informing you of the missing requirements.
